export const API_ENDPOINTS = {
  auth: {
    telegram: '/api/v1/auth/telegram',
    refresh: '/api/v1/auth/refresh',
    me: '/api/v1/auth/me',
    logout: '/api/v1/auth/logout',
  },
  geography: {
    regions: '/api/v1/geography/regions',
    cities: '/api/v1/geography/cities',
    districts: '/api/v1/geography/districts',
    neighborhoods: '/api/v1/geography/neighborhoods',
    streets: '/api/v1/geography/streets',
    metroLines: '/api/v1/geography/metro/lines',
    metroStations: '/api/v1/geography/metro/stations',
  },
  propertyTypes: {
    list: '/api/v1/property-types',
    operations: '/api/v1/property-types/operations',
  },
  properties: {
    list: '/api/v1/properties',
    detail: (id: number) => `/api/v1/properties/${id}`,
    create: '/api/v1/properties',
    update: (id: number) => `/api/v1/properties/${id}`,
    delete: (id: number) => `/api/v1/properties/${id}`,
    myProperties: '/api/v1/properties/user/my',
    photos: (id: number) => `/api/v1/properties/${id}/photos`,
    photosUpload: (id: number) => `/api/v1/properties/${id}/photos/upload`,
    priceHistory: (id: number) => `/api/v1/properties/${id}/price`,
  },
  favorites: {
    list: '/api/v1/favorites',
    add: (id: number) => `/api/v1/favorites/${id}`,
    remove: (id: number) => `/api/v1/favorites/${id}`,
    check: (id: number) => `/api/v1/favorites/check/${id}`,
    ids: '/api/v1/favorites/ids',
  },
  collections: {
    list: '/api/v1/collections',
    create: '/api/v1/collections',
    detail: (id: number) => `/api/v1/collections/${id}`,
    update: (id: number) => `/api/v1/collections/${id}`,
    delete: (id: number) => `/api/v1/collections/${id}`,
    addItem: (id: number) => `/api/v1/collections/${id}/items`,
    removeItem: (id: number, propertyId: number) => `/api/v1/collections/${id}/items/${propertyId}`,
  },
  notes: {
    upsert: (propertyId: number) => `/api/v1/properties/${propertyId}/note`,
    get: (propertyId: number) => `/api/v1/properties/${propertyId}/note`,
    delete: (propertyId: number) => `/api/v1/properties/${propertyId}/note`,
  },
  viewings: {
    create: '/api/v1/viewings',
    list: '/api/v1/viewings',
    updateStatus: (id: number) => `/api/v1/viewings/${id}`,
  },
  savedSearches: {
    list: '/api/v1/saved-searches',
    create: '/api/v1/saved-searches',
    detail: (id: number) => `/api/v1/saved-searches/${id}`,
    update: (id: number) => `/api/v1/saved-searches/${id}`,
    delete: (id: number) => `/api/v1/saved-searches/${id}`,
    toggleNotify: (id: number) => `/api/v1/saved-searches/${id}/toggle-notify`,
  },
  search: {
    map: '/api/v1/search/map',
    compare: '/api/v1/search/compare',
  },
  comparison: {
    compare: '/api/v1/search/compare',
  },
  moderation: {
    pending: '/api/v1/moderation/properties/pending',
    published: '/api/v1/moderation/properties/published',
    action: (id: number) => `/api/v1/moderation/properties/${id}/action`,
    reports: '/api/v1/moderation/reports',
    resolveReport: (id: number) => `/api/v1/moderation/reports/${id}/resolve`,
    stats: '/api/v1/moderation/stats',
  },
  monetization: {
    promotions: '/api/v1/monetization/promotions',
    applyPromotion: '/api/v1/monetization/apply',
    propertyPromotions: (id: number) => `/api/v1/monetization/properties/${id}/promotions`,
    subscriptions: '/api/v1/monetization/subscriptions',
    payments: '/api/v1/monetization/payments',
  },
  analytics: {
    overview: '/api/v1/analytics/overview',
    cityStats: '/api/v1/analytics/city-stats',
    popular: '/api/v1/analytics/popular',
    priceDistribution: '/api/v1/analytics/price-distribution',
    typeDistribution: '/api/v1/analytics/type-distribution',
  },
  admin: {
    dashboard: '/api/v1/admin/dashboard',
    users: '/api/v1/admin/users',
    userDetail: (id: number) => `/api/v1/admin/users/${id}`,
    userRole: (id: number) => `/api/v1/admin/users/${id}/role`,
    userBlock: (id: number) => `/api/v1/admin/users/${id}/block`,
    properties: '/api/v1/admin/properties',
    propertyDetail: (id: number) => `/api/v1/admin/properties/${id}`,
    propertyStatus: (id: number) => `/api/v1/admin/properties/${id}/status`,
    reports: '/api/v1/admin/reports',
    resolveReport: (id: number) => `/api/v1/admin/reports/${id}/resolve`,
  },
  health: '/health',
} as const;