"""Pydantic schemas for API."""
# Auth schemas
from app.schemas.auth import (
    AuthResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    TelegramAuthRequest,
    TelegramInitData,
    TelegramUser,
    TokenResponse,
)

# Common schemas
from app.schemas.common import (
    BaseSchema,
    ErrorResponse,
    MessageResponse,
    PaginatedResponse,
    SuccessResponse,
)

# Geography schemas
from app.schemas.geography import (
    CityBase,
    CityCreate,
    CityRead,
    CityResponse,
    DistrictBase,
    DistrictCreate,
    DistrictRead,
    DistrictResponse,
    MetroLineBase,
    MetroLineCreate,
    MetroLineRead,
    MetroLineResponse,
    MetroStationCreate,
    MetroStationRead,
    MetroStationResponse,
    NeighborhoodBase,
    NeighborhoodCreate,
    NeighborhoodRead,
    NeighborhoodResponse,
    RegionBase,
    RegionCreate,
    RegionRead,
    RegionResponse,
    StreetBase,
    StreetCreate,
    StreetRead,
    StreetResponse,
)

# Moderation schemas
from app.schemas.moderation import (
    ModerationActionResponse,
    PropertyModerationRequest,
    ReportResponse,
)

# Agency schemas
from app.schemas.agency import (
    AgencyCreate,
    AgencyMemberAdd,
    AgencyMemberRead,
    AgencyRead,
    AgencyShort,
    AgencyUpdate,
)

# Monetization schemas
from app.schemas.monetization import (
    PaymentCheckoutResponse,
    PaymentRead,
    PromotionCatalogItem,
    PromotionRead,
    PromoteRequest,
    SubscriptionCreate,
    SubscriptionPlanInfo,
    SubscriptionRead,
)

# Property schemas
from app.schemas.property import (
    FavoriteResponse,
    PriceUpdateRequest,
    PropertyBase,
    PropertyCreate,
    PropertyFeatureBase,
    PropertyFeatureCreate,
    PropertyFeatureRead,
    PropertyFilter,
    PropertyFilterParams,
    PropertyPhotoBase,
    PropertyPhotoCreate,
    PropertyPhotoRead,
    PropertyPriceAnalysisResponse,
    PropertyPriceBase,
    PropertyPriceHistoryResponse,
    PropertyPriceRead,
    PropertyRead,
    PropertyResponse,
    PropertyShortRead,
    PropertyUpdate,
    SavedSearchBase,
    SavedSearchCreate,
    SavedSearchRead,
    SavedSearchResponse,
    SavedSearchUpdate,
)

# Property type schemas
from app.schemas.property_types import (
    OperationTypeBase,
    OperationTypeCreate,
    OperationTypeRead,
    OperationTypeResponse,
    PropertyTypeBase,
    PropertyTypeCreate,
    PropertyTypeRead,
    PropertyTypeResponse,
)

# User schemas
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserProfileBase,
    UserProfileRead,
    UserProfileUpdate,
    UserRead,
    UserResponse,
    UserUpdate,
)

__all__ = [
    "AgencyCreate",
    "AgencyMemberAdd",
    "AgencyMemberRead",
    "AgencyRead",
    "AgencyShort",
    "AgencyUpdate",
    "AuthResponse",
    "BaseSchema",
    "CityBase",
    "CityCreate",
    "CityRead",
    "CityResponse",
    "DistrictBase",
    "DistrictCreate",
    "DistrictRead",
    "DistrictResponse",
    "ErrorResponse",
    "FavoriteResponse",
    "MessageResponse",
    "MetroLineBase",
    "MetroLineCreate",
    "MetroLineRead",
    "MetroLineResponse",
    "MetroStationCreate",
    "MetroStationRead",
    "MetroStationResponse",
    "ModerationActionResponse",
    "NeighborhoodBase",
    "NeighborhoodCreate",
    "NeighborhoodRead",
    "NeighborhoodResponse",
    "OperationTypeBase",
    "OperationTypeCreate",
    "OperationTypeRead",
    "OperationTypeResponse",
    "PaginatedResponse",
    "PaymentCheckoutResponse",
    "PaymentRead",
    "PriceUpdateRequest",
    "PromotionCatalogItem",
    "PromotionRead",
    "PromoteRequest",
    "PropertyBase",
    "PropertyCreate",
    "PropertyFeatureBase",
    "PropertyFeatureCreate",
    "PropertyFeatureRead",
    "PropertyFilter",
    "PropertyFilterParams",
    "PropertyModerationRequest",
    "PropertyPhotoBase",
    "PropertyPhotoCreate",
    "PropertyPhotoRead",
    "PropertyPriceAnalysisResponse",
    "PropertyPriceBase",
    "PropertyPriceHistoryResponse",
    "PropertyPriceRead",
    "PropertyRead",
    "PropertyResponse",
    "PropertyShortRead",
    "PropertyTypeBase",
    "PropertyTypeCreate",
    "PropertyTypeRead",
    "PropertyTypeResponse",
    "PropertyUpdate",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "RegionBase",
    "RegionCreate",
    "RegionRead",
    "RegionResponse",
    "ReportResponse",
    "SavedSearchBase",
    "SavedSearchCreate",
    "SavedSearchRead",
    "SavedSearchResponse",
    "SavedSearchUpdate",
    "StreetBase",
    "StreetCreate",
    "StreetRead",
    "StreetResponse",
    "SubscriptionCreate",
    "SubscriptionPlanInfo",
    "SubscriptionRead",
    "SuccessResponse",
    "TelegramAuthRequest",
    "TelegramInitData",
    "TelegramUser",
    "TokenResponse",
    "UserBase",
    "UserCreate",
    "UserProfileBase",
    "UserProfileRead",
    "UserProfileUpdate",
    "UserRead",
    "UserResponse",
    "UserUpdate",
]
